# Basic Information
title: Aref Azizpour
position: Ph.D. Student in Computer Science
affiliation: Drexel University
email: aa4639 (at) drexel.edu

# Search Engine Optimization (SEO)
keywords: aref azizpour, computer vision, ai-generated media, synthetic media detection, deepfake detection, ai forensics
description:description: I am a Ph.D. student in Computer Science at Drexel University. My research focuses on AI-generated media detection, synthetic media forensics, and open-world machine learning.
canonical: https://arefazizpour.github.io/

# Links
google_scholar: https://scholar.google.com/citations?user=5EDdOgkAAAAJ&hl=en
cv_link: assets/files/Aref-Azizpour-PhD-Resume.pdf
github_link: https://github.com/arefazizpour
linkedin: https://www.linkedin.com/in/aref-azizpour/

# Images
avatar: ./assets/img/avatar.png
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png

# Footnote
enable_footnote: true

# Auto Dark Mode
auto_dark_mode: true

# Font
font: "Sans Serif"

# Use this project as a remote theme for GitHub Pages
remote_theme: yaoyao-liu/minimal-light

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
  - html_source_file/
